entryPoints:
  web:
    address: ":8081"
  websecure:
    address: ":443"


providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

api:
  insecure: true
  dashboard: true

tls:
  certificates:
  - certFile: /certs/localhost.crt
    keyFile: /certs/localhost.key
